#!/bin/sh
#
# Starts audio services
#

case "$1" in
    start)
        alsactl init # init cards with alsa files
        amixer sset 'speaker on off switch' 'on'
	amixer sset 'DAC FL Gain' 128
	amixer sset 'DAC PA' 10
    ;;
    stop)
    ;;
    restart|reload)
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
